version: '2'

services:
  unbound:
    restart: always
    image: akira345/unbound:latest
    ports:
      - "192.168.xxx.xxx:53:53"
      - "192.168.xxx.xxx:53:53/udp"
    volumes:
      - "$PWD/conf:/conf:ro"
